import { CORES_POR_IDIOMA, COR_BASE_CARDS } from './themeColors';

export const RANKS_SELECT = [1, 4, 5, 10, 13, 14, 19, 22, 23];
export const RANKS_WRITE = [2, 6, 7, 11, 15, 16, 20, 24, 25];
export const RANKS_VOICE = [3, 8, 9, 12, 17, 18, 21, 26, 27];

export const NOMES_RANKS = [
  "Listen-Translate > Complete 30%", "Listen-Translate > Write 30%", "Listen-Translate > Speak 30%", "Translate > Complete 30%", "Listen > Complete 30%", "Translate > Write 30%", "Listen > Write 30%", "Translate > Speak 30%", "Listen > Speak 30%",
  "Listen-Translate > Complete 70%", "Listen-Translate > Write 70%", "Listen-Translate > Speak 70%", "Translate > Complete 70%", "Listen > Complete 70%", "Translate > Write 70%", "Listen > Write 70%", "Translate > Speak 70%", "Listen > Speak 70%",
  "Listen-Translate > Complete 100%", "Listen-Translate > Write 100%", "Listen-Translate > Speak 100%", "Translate > Complete 100%", "Listen > Complete 100%", "Translate > Write 100%", "Listen > Write 100%", "Translate > Speak 100%", "Listen > Speak 100%"
];

export const ESTRUTURA_NIVEIS = {
  default: ['A1', 'A2', 'B1', 'B2'],
};

export const temas = {
  pt: { label: "Eu falo Português", bg: CORES_POR_IDIOMA.pt.bgPrincipal, btn: COR_BASE_CARDS, corTextoL1: CORES_POR_IDIOMA.pt.acaoEscura, langCode: "pt-BR", nomes: { pt: "Português", en: "Inglês", es: "Espanhol", fr: "Francês", it: "Italiano", ge: "Alemão", pi: "Pinyin" } },
  en: { label: "I speak English", bg: CORES_POR_IDIOMA.en.bgPrincipal, btn: COR_BASE_CARDS, corTextoL1: CORES_POR_IDIOMA.en.acaoEscura, langCode: "en-US", nomes: { pt: "Portuguese", en: "English", es: "Spanish", fr: "French", it: "Italian", ge: "German", pi: "Pinyin" } },
  es: { label: "Hablo Español", bg: CORES_POR_IDIOMA.es.bgPrincipal, btn: COR_BASE_CARDS, corTextoL1: CORES_POR_IDIOMA.es.acaoEscura, langCode: "es-ES", nomes: { pt: "Portugués", en: "Inglés", es: "Español", fr: "Francés", it: "Italiano", ge: "Alemán", pi: "Pinyin" } },
  fr: { label: "Je parle Français", bg: CORES_POR_IDIOMA.fr.bgPrincipal, btn: COR_BASE_CARDS, corTextoL1: CORES_POR_IDIOMA.fr.acaoEscura, langCode: "fr-FR", nomes: { pt: "Portugais", en: "Anglais", es: "Espagnol", fr: "Français", it: "Italien", ge: "Allemand", pi: "Pinyin" } },
  it: { label: "Parlo Italiano", bg: CORES_POR_IDIOMA.it.bgPrincipal, btn: COR_BASE_CARDS, corTextoL1: CORES_POR_IDIOMA.it.acaoEscura, langCode: "it-IT", nomes: { pt: "Portoghese", en: "Inglese", es: "Spagnolo", fr: "Francese", it: "Italiano", ge: "Tedesco", pi: "Pinyin" } },
  ge: { label: "Ich spreche Deutsch", bg: CORES_POR_IDIOMA.ge.bgPrincipal, btn: COR_BASE_CARDS, corTextoL1: CORES_POR_IDIOMA.ge.acaoEscura, langCode: "de-DE", nomes: { pt: "Portugiesisch", en: "Englisch", es: "Spanisch", fr: "Französisch", it: "Italienisch", ge: "Deutsch", pi: "Pinyin" } },
  pi: { label: "我说中文", bg: CORES_POR_IDIOMA.pi.bgPrincipal, btn: COR_BASE_CARDS, corTextoL1: CORES_POR_IDIOMA.pi.acaoEscura, langCode: "zh-CN", nomes: { pt: "葡萄牙语", en: "英语", es: "西班牙语", fr: "法语", it: "Italiano", ge: "德语", pi: "中文" } },
};

export const interfaceTraducoes = {
  pt: { fill: "Escreva", order: "Complete", pronounce: "Diga", repeat: "Repita", translate: "Traduza", wantStudy: "Eu quero estudar", back: "Voltar", home: "Início", levels: "Níveis", topics: "Tópicos", quit: "Sair", show: "Mostrar Tradução", hide: "Esconder Tradução", prev: "Anterior", next: "Próximo", normal: "Ouvir", slow: "Lento", askAi: "Explicação IA", practice: "Praticar", check: "Verificar", review: "Rever", speakNow: "Falar agora", cantSpeak: "Não posso falar agora", listening: "Ouvindo...", listenRepeat: "Ouça e Repita", analyzing: "Analisando...", phraseCards: "Cartões de Frases", profile: "Perfil", resetProgress: "Resetar Progresso", confirmReset: "Deseja resetar todo o seu progresso neste idioma? Esta ação não pode ser desfeita.", game: "Jogo", immersion: "Imersão (em breve)", promptBase: 'Explique resumidamente a frase: "(sentence)" no nível (level), da forma mais simples possível, com traduções dos elementos separados.' },
  en: { fill: "Write", order: "Complete", pronounce: "Speak", repeat: "Repeat", translate: "Translate", wantStudy: "I want to study", back: "Back", home: "Home", levels: "Levels", topics: "Topics", quit: "Quit", show: "Show Translation", hide: "Hide Translation", prev: "Previous", next: "Next", normal: "Listen", slow: "Slow", askAi: "AI Explanation", practice: "Practice", check: "Check", review: "Review", speakNow: "Speak now", cantSpeak: "Can't talk now", listening: "Listening...", listenRepeat: "Listen and Repeat", analyzing: "Analisando...", phraseCards: "Phrase Cards", profile: "Profile", resetProgress: "Reset Progress", confirmReset: "Do you want to reset all your progress in this language? This action cannot be undone.", game: "Game", immersion: "Immersion (soon)", promptBase: 'Briefly explain the sentence: "(sentence)" at level (level), as simply as possible, with translations of the separated elements.' },
  es: { fill: "Escribe", order: "Completa", pronounce: "Di", repeat: "Repite", translate: "Traduce", wantStudy: "Quiero estudiar", back: "Volver", home: "Inicio", levels: "Niveles", topics: "Temas", quit: "Salir", show: "Mostrar traducción", hide: "Ocultar traducción", prev: "Anterior", next: "Siguiente", normal: "Escuchar", slow: "Lento", askAi: "Explicación IA", practice: "Practicar", check: "Verificar", review: "Repasar", speakNow: "Hablar agora", cantSpeak: "No podemos falar", listening: "Escuchando...", listenRepeat: "Escucha y repite", analyzing: "Analizando...", phraseCards: "Tarjetas de Frases", profile: "Perfil", resetProgress: "Restablecer Progreso", confirmReset: "¿Deseas restablecer todo tu progreso en este idioma? Esta acción no se puede deshacer.", game: "Juego", immersion: "Inmersión (pronto)", promptBase: 'Explique brevemente la frase: "(sentence)" en el nivel (level), de la manera más sencilla posible, con traduções de los elementos separados.' },
  fr: { fill: "Écris", order: "Complète", pronounce: "Dis", repeat: "Répète", translate: "Traduis", wantStudy: "Je veux estudar", back: "Retour", home: "Accueil", levels: "Niveaux", topics: "Sujets", quit: "Quitter", show: "Afficher la traduction", hide: "Masquer la traduction", prev: "Précédent", next: "Suivant", normal: "Écouter", slow: "Lent", askAi: "Explication IA", practice: "Pratiquer", check: "Vérifier", review: "Réviser", speakNow: "Parler maintenant", cantSpeak: "Je ne peux pas falar agora", listening: "Écoute...", listenRepeat: "Écoutez et répétez", analyzing: "Analyse...", phraseCards: "Cartes de Phrases", profile: "Profil", resetProgress: "Réinitialiser le Progrès", confirmReset: "Voulez-vous réinitialiser tous vos progrès dans cette langue ? Cette action est irréversible.", game: "Jeu", immersion: "Immersion (bientôt)", promptBase: 'Expliquez brièvement la frase : "(sentence)" au niveau (level), aussi simplement que possible, avec des traduções des éléments séparés.' },
  it: { fill: "Scrivi", order: "Completa", pronounce: "Di'", repeat: "Ripeti", translate: "Traduci", wantStudy: "Voglio studiare", back: "Indietro", home: "Home", levels: "Livelli", topics: "Argomenti", quit: "Esci", show: "Mostra traduzione", hide: "Nascondi traduzione", prev: "Precedente", next: "Successivo", normal: "Ascolta", slow: "Lento", askAi: "Spiegazione IA", practice: "Pratica", check: "Verifica", review: "Ripassa", speakNow: "Parla ora", cantSpeak: "Non posso falar agora", listening: "Ascolto...", listenRepeat: "Ascolta e repeti", analyzing: "Analisi...", phraseCards: "Carte di Frasi", profile: "Profilo", resetProgress: "Ripristina Progressi", confirmReset: "Vuoi resettare tutti i tuoi progressi in questa lingua? Questa ação non può essere annullata.", game: "Gioco", immersion: "Immersione (presto)", promptBase: 'Spiega brevemente la frase: "(sentence)" al livello (level), nel modo più simples possível, con le traduções dei singoli elementos.' },
  ge: { fill: "Schreib", order: "Vervollständige", pronounce: "Sag", repeat: "Wiederhol", translate: "Übersetz", wantStudy: "Ich möchte lernen", back: "Zurück", home: "Start", levels: "Stufen", topics: "Themen", quit: "Beenden", show: "Übersetzung anzeigen", hide: "Übersetzung ausblenden", prev: "Zurück", next: "Weiter", normal: "Hören", slow: "Langsam", askAi: "KI-Erklärung", practice: "Üben", check: "Prüfen", review: "Wiederholen", speakNow: "Jetzt sprechen", cantSpeak: "Ich kann gerade não sprechen", listening: "Hören...", listenRepeat: "Hören und wiederholen", analyzing: "Analysieren...", phraseCards: "Satzkarten", profile: "Profil", resetProgress: "Fortschritt zurücksetzen", confirmReset: "Möchten Sie Ihren gesamten Fortschritt in dieser Sprache zurücksetzen? Diese Aktion kann nicht rückgängig gemacht werden.", game: "Spiel", immersion: "Immersion (bald)", promptBase: 'Erklären Sie kurz den Satz: "(sentence)" auf Stufe (level), so einfach wie möglich, mit Übersetzungen der einzelnen Elemente.' },
  pi: { fill: "写", order: "完成", pronounce: "说", repeat: "复述", translate: "翻译", wantStudy: "我想学", back: "返回", home: "首页", levels: "等级", topics: "话题", quit: "退出", show: "显示翻译", hide: "隐藏翻译", prev: "上一个", next: "下一个", normal: "听", slow: "慢", askAi: "AI 解释", practice: "练习", check: "检查", review: "复ixo", speakNow: "现在说话", cantSpeak: "现在不能说话", listening: "正在听...", listenRepeat: "听并复述", analyzing: "分析中...", phraseCards: "句卡 (Jù kǎ)", profile: "个人资料 (Gèrén zīliào)", resetProgress: "重置进度 (Chóngzhì jìndù)", confirmReset: "您确定要重置此语言的所有进度吗？此操作无法撤消。", game: "游戏 (Yóuxì)", immersion: "沉浸 (Chénjìn) (即将推出)", promptBase: '简要解释句子："(sentence)" 在级别 (level)，尽可能简单，并附上各个元素的翻译。' }
};
